# Generated by Django 3.0.5 on 2020-06-08 17:22

import EventPayment.enums
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('role', enumchoicefield.fields.EnumChoiceField(enum_class=EventPayment.enums.Role, max_length=8)),
                ('total_spots', models.IntegerField()),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=300, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='event.Event')),
            ],
            options={
                'verbose_name': 'Event pass',
                'verbose_name_plural': 'Event passes',
            },
        ),
        migrations.CreateModel(
            name='CoursePass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('role', enumchoicefield.fields.EnumChoiceField(enum_class=EventPayment.enums.Role, max_length=8)),
                ('total_spots', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='event.Course')),
            ],
            options={
                'verbose_name': 'Course pass',
                'verbose_name_plural': 'Course passes',
            },
        ),
    ]
