# Generated by Django 3.0.5 on 2020-05-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pass_type', '0002_auto_20200502_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coursepass',
            name='name',
        ),
    ]
