version: '3'

services:
  backend:
    build: ./backend/
    command: python backend/EventPayment/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/EventPayment
    ports:
      - "8000:8000"
    depends_on:
    - db
  db:
    image: postgres
  frontend:
    build: ./frontend/
    stdin_open: true
    command: npm start --prefix frontend/event-payment
    volumes:
      - .:/event-payment
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    depends_on:
    - backend


