# Generated by Django 3.0.5 on 2020-06-08 17:22

import EventPayment.enums
from django.db import migrations, models
import enumchoicefield.fields
import event.models.course


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=300)),
                ('address', models.CharField(default='https://goo.gl/maps/NdrHbAVgVRkX6STg7', max_length=80)),
                ('week_start', models.IntegerField()),
                ('week_end', models.IntegerField()),
                ('day', enumchoicefield.fields.EnumChoiceField(enum_class=EventPayment.enums.Day, max_length=9)),
                ('year', models.IntegerField(default=event.models.course.this_year)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=300)),
                ('address', models.CharField(default='https://goo.gl/maps/NdrHbAVgVRkX6STg7', max_length=80)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
