# Generated by Django 3.0.5 on 2020-05-02 21:15

from django.db import migrations, models
import event.models.course


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=event.models.course.this_year),
        ),
    ]
