# Generated by Django 3.0.5 on 2020-05-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepass',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='eventpass',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
