# Generated by Django 3.0.5 on 2020-05-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_type', '0003_auto_20200503_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepass',
            name='max_amount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpass',
            name='max_amount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
