# Generated by Django 3.0.5 on 2020-05-02 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pass_type', '0002_auto_20200502_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractPassPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('buyer_name', models.CharField(max_length=80)),
                ('buyer_phone', models.CharField(max_length=80)),
                ('buyer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EventPassPayment',
            fields=[
                ('abstractpasspayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.AbstractPassPayment')),
                ('pass_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_type.EventPass')),
            ],
            bases=('payment.abstractpasspayment',),
        ),
        migrations.CreateModel(
            name='CoursePassPayment',
            fields=[
                ('abstractpasspayment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.AbstractPassPayment')),
                ('pass_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_type.CoursePass')),
            ],
            bases=('payment.abstractpasspayment',),
        ),
    ]
