# Generated by Django 3.0.5 on 2020-05-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200503_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractpasspayment',
            old_name='paid_manually',
            new_name='paid_online',
        ),
    ]
