# Generated by Django 3.0.5 on 2020-05-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursepasspayment',
            options={'verbose_name': 'Course payment', 'verbose_name_plural': 'Course payments'},
        ),
        migrations.AlterModelOptions(
            name='eventpasspayment',
            options={'verbose_name': 'Event payment', 'verbose_name_plural': 'Event payments'},
        ),
    ]
