# Generated by Django 3.0.5 on 2020-05-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20200503_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abstractpasspayment',
            old_name='paid',
            new_name='paid_manually',
        ),
    ]
